# -*- coding: utf-8 -*-
"""AutoExchange – 自動匯率抓取.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g2k8gsWcIoGJJ3_hqnfdrOzqqI9M0WxM
"""

import requests
import pandas as pd
import datetime
import schedule
import time

def fetch_exchange_rate():
    # 1. 抓取 API
    url = "https://api.exchangerate-api.com/v4/latest/USD"
    response = requests.get(url).json()

    # 2. 整理資料
    data = pd.DataFrame(response["rates"].items(), columns=["Currency", "Rate"])
    data["Base"] = response["base"]
    data["Date"] = response["date"]

    # 3. 存檔 (每天一份)
    today = datetime.date.today().strftime("%Y-%m-%d")
    filename = f"exchange_rate_{today}.csv"
    data.to_csv(filename, index=False, encoding="utf-8-sig")

    print(f"✅ 匯率資料已更新，存檔於 {filename}")

# 設定排程：每天早上 9 點執行
schedule.every().day.at("09:00").do(fetch_exchange_rate)

print("⏳ 自動化匯率抓取已啟動...")

while True:
    schedule.run_pending()
    time.sleep(60)  # 每 60 秒檢查一次
